Adding pr template for the repo
OneSignal/onesignal-expo-plugin pull request #99
Opened 2022-07-05 15:49 UTC by emawby

This is a very generic template with no Expo specific fields. Feel free to suggest edits for anything we should add/remove

2022-08-22 18:25 UTC, rgomezp requested changes

2022-08-22 18:25 UTC, rgomezp commented on .github/pull_request_template.md
> +**RECOMMEND - OPTIONAL -** What is intended to be effected. What is known not to change. Example: Notifications are grouped when parameter X is set, not enabled by default.
Nit: add interrogation points

2022-08-22 18:25 UTC, rgomezp commented on .github/pull_request_template.md
> +   - [ ] I have personally tested this on my device, or explained why that is not possible
Perhaps we should add something like "Tested on latest version"

2022-08-22 18:26 UTC, rgomezp commented on .github/pull_request_template.md
> +   - [ ] I have personally tested this on my device, or explained why that is not possible
Also, was this tested on iOS? Android? Both?

2022-10-03 14:07 UTC, brismithers approved these changes

2022-10-03 14:07 UTC, brismithers approved these changes

2022-10-03 17:51 UTC, rgomezp approved these changes

2022-10-03 17:52 UTC, merged